name: Build Cordova Android APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install dependencies
        run: npm install

      - name: Add Android platform
        run: cordova platform add android@12.0.1

      - name: Build APK
        run: cordova build android

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: neonchat-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
